//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RugpViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RugpViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Analysis 的本地化字符串。
        /// </summary>
        public static string AnalysisMenuLabel {
            get {
                return ResourceManager.GetString("AnalysisMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysis 的本地化字符串。
        /// </summary>
        public static string AnalysisTabLabel {
            get {
                return ResourceManager.GetString("AnalysisTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure? 的本地化字符串。
        /// </summary>
        public static string AreYouSureTitle {
            get {
                return ResourceManager.GetString("AreYouSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string FileMenuLabel {
            get {
                return ResourceManager.GetString("FileMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find All Images 的本地化字符串。
        /// </summary>
        public static string FindAllImagesButtonLabel {
            get {
                return ResourceManager.GetString("FindAllImagesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find All Images... 的本地化字符串。
        /// </summary>
        public static string FindAllImagesMenuLabel {
            get {
                return ResourceManager.GetString("FindAllImagesMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find all images. 的本地化字符串。
        /// </summary>
        public static string FindAllImagesToolTip {
            get {
                return ResourceManager.GetString("FindAllImagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finding all images... 的本地化字符串。
        /// </summary>
        public static string FindingAllImagesEllipsis {
            get {
                return ResourceManager.GetString("FindingAllImagesEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex Dump 的本地化字符串。
        /// </summary>
        public static string HexDumpTabLabel {
            get {
                return ResourceManager.GetString("HexDumpTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        public static string ImageTabLabel {
            get {
                return ResourceManager.GetString("ImageTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string InfoTabLabel {
            get {
                return ResourceManager.GetString("InfoTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open... 的本地化字符串。
        /// </summary>
        public static string OpenMenuLabel {
            get {
                return ResourceManager.GetString("OpenMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a .rio file. 的本地化字符串。
        /// </summary>
        public static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resources 的本地化字符串。
        /// </summary>
        public static string ResourcesTabLabel {
            get {
                return ResourceManager.GetString("ResourcesTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rUGPViewer 的本地化字符串。
        /// </summary>
        public static string rUGPViewer {
            get {
                return ResourceManager.GetString("rUGPViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Image 的本地化字符串。
        /// </summary>
        public static string SaveImageButtonLabel {
            get {
                return ResourceManager.GetString("SaveImageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Image... 的本地化字符串。
        /// </summary>
        public static string SaveImageMenuLabel {
            get {
                return ResourceManager.GetString("SaveImageMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the image as a .png file. 的本地化字符串。
        /// </summary>
        public static string SaveImageToolTip {
            get {
                return ResourceManager.GetString("SaveImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Muvluv Alternative .rio file. 的本地化字符串。
        /// </summary>
        public static string SelectRioFileSentence {
            get {
                return ResourceManager.GetString("SelectRioFileSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: this analysis currently loads all objects into memory. For MLA, this will use about 5.5 GB of memory. You should only proceed if your system has at least 8 GB of memory.
        ///
        ///The process will take tens of minutes. Afterwards, you will be shown a list of discovered images.
        ///
        ///Do you want to proceed? 的本地化字符串。
        /// </summary>
        public static string WarningAnalysisMemoryUsage {
            get {
                return ResourceManager.GetString("WarningAnalysisMemoryUsage", resourceCulture);
            }
        }
    }
}
