#提取时使用的文本编码
encoding='932'

#[0]
#pat="32siiiii16s32s256s"
#text=[0]

[1]  #需要提取的节索引
pat="64sI32s"  #该节的item定义，使用python的struct表示方法
text=[0] #需要提取上述item中的文本的索引


#[1]
#pat="64s32sIIIII"
#text=[0]