#include	"pch.h"
#include	"ng_macro.h"



// タイル通常表示（加算）
void tcgd_normal_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルスプライト表示（加算）
void tcgd_sprite_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル透明通常表示（加算）
void tcgd_normal_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル透明スプライト表示（加算）
void tcgd_sprite_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色通常表示（加算）
void tcgd_normal_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色スプライト表示（加算）
void tcgd_sprite_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色透明通常表示（加算）
void tcgd_normal_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色透明スプライト表示（加算）
void tcgd_sprite_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル明暗通常表示（加算）
void tcgd_normal_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル明暗スプライト表示（加算）
void tcgd_sprite_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル明暗透明通常表示（加算）
void tcgd_normal_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル明暗透明スプライト表示（加算）
void tcgd_sprite_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色明暗通常表示（加算）
void tcgd_normal_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色明暗スプライト表示（加算）
void tcgd_sprite_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色明暗透明通常表示（加算）
void tcgd_normal_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル変色明暗透明スプライト表示（加算）
void tcgd_sprite_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ通常表示（加算）
void tcgd_normal_mono_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノスプライト表示（加算）
void tcgd_sprite_mono_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ透明通常表示（加算）
void tcgd_normal_mono_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ透明スプライト表示（加算）
void tcgd_sprite_mono_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色通常表示（加算）
void tcgd_normal_mono_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色スプライト表示（加算）
void tcgd_sprite_mono_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色透明通常表示（加算）
void tcgd_normal_mono_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色透明スプライト表示（加算）
void tcgd_sprite_mono_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ明暗通常表示（加算）
void tcgd_normal_mono_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ明暗スプライト表示（加算）
void tcgd_sprite_mono_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ明暗透明通常表示（加算）
void tcgd_normal_mono_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ明暗透明スプライト表示（加算）
void tcgd_sprite_mono_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色明暗通常表示（加算）
void tcgd_normal_mono_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色明暗スプライト表示（加算）
void tcgd_sprite_mono_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色明暗透明通常表示（加算）
void tcgd_normal_mono_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイルモノ変色明暗透明スプライト表示（加算）
void tcgd_sprite_mono_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転通常表示（加算）
void tcgd_normal_reverse_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転スプライト表示（加算）
void tcgd_sprite_reverse_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転透明通常表示（加算）
void tcgd_normal_reverse_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転透明スプライト表示（加算）
void tcgd_sprite_reverse_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色通常表示（加算）
void tcgd_normal_reverse_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色スプライト表示（加算）
void tcgd_sprite_reverse_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色透明通常表示（加算）
void tcgd_normal_reverse_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色透明スプライト表示（加算）
void tcgd_sprite_reverse_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転明暗通常表示（加算）
void tcgd_normal_reverse_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転明暗スプライト表示（加算）
void tcgd_sprite_reverse_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転明暗透明通常表示（加算）
void tcgd_normal_reverse_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転明暗透明スプライト表示（加算）
void tcgd_sprite_reverse_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色明暗通常表示（加算）
void tcgd_normal_reverse_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色明暗スプライト表示（加算）
void tcgd_sprite_reverse_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色明暗透明通常表示（加算）
void tcgd_normal_reverse_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転変色明暗透明スプライト表示（加算）
void tcgd_sprite_reverse_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ通常表示（加算）
void tcgd_normal_reverse_mono_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノスプライト表示（加算）
void tcgd_sprite_reverse_mono_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ透明通常表示（加算）
void tcgd_normal_reverse_mono_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ透明スプライト表示（加算）
void tcgd_sprite_reverse_mono_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色通常表示（加算）
void tcgd_normal_reverse_mono_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色スプライト表示（加算）
void tcgd_sprite_reverse_mono_change_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色透明通常表示（加算）
void tcgd_normal_reverse_mono_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色透明スプライト表示（加算）
void tcgd_sprite_reverse_mono_change_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ明暗通常表示（加算）
void tcgd_normal_reverse_mono_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ明暗スプライト表示（加算）
void tcgd_sprite_reverse_mono_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ明暗透明通常表示（加算）
void tcgd_normal_reverse_mono_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ明暗透明スプライト表示（加算）
void tcgd_sprite_reverse_mono_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色明暗通常表示（加算）
void tcgd_normal_reverse_mono_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR00
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色明暗スプライト表示（加算）
void tcgd_sprite_reverse_mono_change_bright_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR01
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色明暗透明通常表示（加算）
void tcgd_normal_reverse_mono_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR02
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}

// タイル反転モノ変色明暗透明スプライト表示（加算）
void tcgd_sprite_reverse_mono_change_bright_clr_tile_add(void){
		_asm{
			GRPMAC_LOOP_START_TILE GRPMAC_TILECLR03
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_ADDCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_ADDCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_ADDCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END_TILE
		}
}


