#include	"pch.h"
#include	"ng_macro.h"



// 通常表示（減算）
void tcgd_normal_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// スプライト表示（減算）
void tcgd_sprite_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 透明通常表示（減算）
void tcgd_normal_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 透明スプライト表示（減算）
void tcgd_sprite_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 変色通常表示（減算）
void tcgd_normal_change_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 変色スプライト表示（減算）
void tcgd_sprite_change_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 変色透明通常表示（減算）
void tcgd_normal_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 変色透明スプライト表示（減算）
void tcgd_sprite_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 明暗通常表示（減算）
void tcgd_normal_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 明暗スプライト表示（減算）
void tcgd_sprite_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 明暗透明通常表示（減算）
void tcgd_normal_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 明暗透明スプライト表示（減算）
void tcgd_sprite_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 変色明暗通常表示（減算）
void tcgd_normal_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 変色明暗スプライト表示（減算）
void tcgd_sprite_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 変色明暗透明通常表示（減算）
void tcgd_normal_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 変色明暗透明スプライト表示（減算）
void tcgd_sprite_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ通常表示（減算）
void tcgd_normal_mono_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// モノスプライト表示（減算）
void tcgd_sprite_mono_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ透明通常表示（減算）
void tcgd_normal_mono_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// モノ透明スプライト表示（減算）
void tcgd_sprite_mono_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ変色通常表示（減算）
void tcgd_normal_mono_change_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// モノ変色スプライト表示（減算）
void tcgd_sprite_mono_change_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ変色透明通常表示（減算）
void tcgd_normal_mono_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// モノ変色透明スプライト表示（減算）
void tcgd_sprite_mono_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ明暗通常表示（減算）
void tcgd_normal_mono_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// モノ明暗スプライト表示（減算）
void tcgd_sprite_mono_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ明暗透明通常表示（減算）
void tcgd_normal_mono_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// モノ明暗透明スプライト表示（減算）
void tcgd_sprite_mono_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ変色明暗通常表示（減算）
void tcgd_normal_mono_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// モノ変色明暗スプライト表示（減算）
void tcgd_sprite_mono_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// モノ変色明暗透明通常表示（減算）
void tcgd_normal_mono_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// モノ変色明暗透明スプライト表示（減算）
void tcgd_sprite_mono_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転通常表示（減算）
void tcgd_normal_reverse_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転スプライト表示（減算）
void tcgd_sprite_reverse_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転透明通常表示（減算）
void tcgd_normal_reverse_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転透明スプライト表示（減算）
void tcgd_sprite_reverse_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転変色通常表示（減算）
void tcgd_normal_reverse_change_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転変色スプライト表示（減算）
void tcgd_sprite_reverse_change_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転変色透明通常表示（減算）
void tcgd_normal_reverse_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転変色透明スプライト表示（減算）
void tcgd_sprite_reverse_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転明暗通常表示（減算）
void tcgd_normal_reverse_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転明暗スプライト表示（減算）
void tcgd_sprite_reverse_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転明暗透明通常表示（減算）
void tcgd_normal_reverse_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転明暗透明スプライト表示（減算）
void tcgd_sprite_reverse_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転変色明暗通常表示（減算）
void tcgd_normal_reverse_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転変色明暗スプライト表示（減算）
void tcgd_sprite_reverse_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転変色明暗透明通常表示（減算）
void tcgd_normal_reverse_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転変色明暗透明スプライト表示（減算）
void tcgd_sprite_reverse_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR

			GRPMAC_GETSRC_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ通常表示（減算）
void tcgd_normal_reverse_mono_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノスプライト表示（減算）
void tcgd_sprite_reverse_mono_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ透明通常表示（減算）
void tcgd_normal_reverse_mono_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノ透明スプライト表示（減算）
void tcgd_sprite_reverse_mono_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ変色通常表示（減算）
void tcgd_normal_reverse_mono_change_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノ変色スプライト表示（減算）
void tcgd_sprite_reverse_mono_change_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ変色透明通常表示（減算）
void tcgd_normal_reverse_mono_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノ変色透明スプライト表示（減算）
void tcgd_sprite_reverse_mono_change_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ明暗通常表示（減算）
void tcgd_normal_reverse_mono_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノ明暗スプライト表示（減算）
void tcgd_sprite_reverse_mono_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ明暗透明通常表示（減算）
void tcgd_normal_reverse_mono_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノ明暗透明スプライト表示（減算）
void tcgd_sprite_reverse_mono_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ変色明暗通常表示（減算）
void tcgd_normal_reverse_mono_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノ変色明暗スプライト表示（減算）
void tcgd_sprite_reverse_mono_change_bright_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITE
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}

// 反転モノ変色明暗透明通常表示（減算）
void tcgd_normal_reverse_mono_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R

			GRPMAC_LOOP_END
		}
}

// 反転モノ変色明暗透明スプライト表示（減算）
void tcgd_sprite_reverse_mono_change_bright_clr_sub(void){
		_asm{
			GRPMAC_LOOP_START GRPMAC_SPRITECLR
			GRPMAC_MONO_READY
			GRPMAC_GETSRC_B GRPMAC_MONO_B GRPMAC_REVERSE GRPMAC_BETA_B GRPMAC_PAL_B GRPMAC_SUBCLRSET_B
			GRPMAC_GETSRC_G GRPMAC_MONO_G GRPMAC_REVERSE GRPMAC_BETA_G GRPMAC_PAL_G GRPMAC_SUBCLRSET_G
			GRPMAC_GETSRC_R GRPMAC_MONO_R GRPMAC_REVERSE GRPMAC_BETA_R GRPMAC_PAL_R GRPMAC_SUBCLRSET_R
		grplv_step_nopixel:
			GRPMAC_LOOP_END
		}
}


