# BGI script file opcode table

import asdis
import re

re_fcn = re.compile('([A-Za-z_][A-Za-z0-9_:]*)\(.*\)')

offsets = set()

def clear_offsets():
	offsets.clear()

def get_string(code, addr, defines, *args):
	pos0 = args[0]
	pos1 = code.find(b'\x00', pos0)
	string = code[pos0:pos1].decode('cp932')
	string = asdis.escape(string)
	return string
	
def get_file(code, addr, defines, *args):
	pos0 = args[0]
	pos1 = code.find(b'\x00', pos0)
	string = code[pos0:pos1].decode('cp932')
	string = asdis.escape(string)
	lno = args[1]
	return string, lno
	
def get_offset(code, addr, defines, *args):
	offset = args[0]
	offsets.add(offset)
	if offset in defines:
		offset_s = defines[offset]
	else:
		offset_s = 'L%05x' % offset
	return offset_s
	
ops = {
0x000: ('<i', 'push_dword(%d)', None),
0x001: ('<I', 'push_offset(%s)', get_offset),
0x002: ('<i', 'push_base_offset(%d)', None),
0x003: ('<I', 'push_string("%s")', get_string),
0x008: ('<i', 'load(%d)', None),
0x009: ('<i', 'move(%d)', None),
0x00A: ('<i', 'move_arg(%d)', None),
0x010: ('', 'load_base()', None),
0x011: ('', 'store_base()', None),
0x018: ('', 'jmp()', None),
0x019: ('<I', 'jc(%#x)', None),
0x01A: ('', 'call()', None),
0x01B: ('', 'ret()', None),
0x01E: ('', 'reg_exception_handler()', None),
0x01F: ('', 'unreg_exception_handler()', None),
0x020: ('', 'add()', None),
0x021: ('', 'sub()', None),
0x022: ('', 'mul()', None),
0x023: ('', 'div()', None),
0x024: ('', 'mod()', None),
0x025: ('', 'and()', None),
0x026: ('', 'or()', None),
0x027: ('', 'xor()', None),
0x028: ('', 'not()', None),
0x029: ('', 'shl()', None),
0x02A: ('', 'shr()', None),
0x02B: ('', 'sar()', None),
0x030: ('', 'eq()', None),
0x031: ('', 'neq()', None),
0x032: ('', 'leq()', None),
0x033: ('', 'geq()', None),
0x034: ('', 'lt()', None),
0x035: ('', 'gt()', None),
0x038: ('', 'bool_and()', None),
0x039: ('', 'bool_or()', None),
0x03A: ('', 'bool_zero()', None),
0x03F: ('<i', 'nargs(%d)', None),
0x07F: ('<Ii', 'line("%s", %d)', get_file),

0x0080: ('', 'CopyMemory()', None),
0x0081: ('', 'ClearMemory()', None),
0x0082: ('', 'FillMemory()', None),
0x0083: ('', 'CompareMemory()', None),
0x0090: ('', 'CopyStrings()', None),
0x0091: ('', 'MergeStrings()', None),
0x0092: ('', 'ChangeToLowercase()', None),
0x0093: ('', 'SubstituteStringsBForStringsA()', None),
0x0094: ('', 'GetLengthOfStrings()', None),
0x0095: ('', 'CompareStrings()', None),
0x0098: ('', 'GenerateStringsFromNumber()', None),
0x0099: ('', 'GetStringsPartially()', None),
0x00A0: ('', 'GetRandomNumber()', None),
0x00A8: ('', 'ConvertStringsToNumber()', None),
0x00E0: ('', 'StoreValueToLocalWork()', None),
0x00E1: ('', 'LoadValueFromLocalWork()', None),
0x00E2: ('', 'StoreValueToGlobalWork()', None),
0x00E3: ('', 'LoadValueFromGlobalWork()', None),
0x00E4: ('', 'SetLocalFlag()', None),
0x00E5: ('', 'GetLocalFlag()', None),
0x00E6: ('', 'SetGlobalFlag()', None),
0x00E7: ('', 'GetGlobalFlag()', None),
0x00E8: ('', 'GetPointerToLocalStrings()', None),
0x00EC: ('', 'GetRegisteredStrings()', None),
0x00EF: ('', 'GetHashValue()', None),
0x00F0: ('', 'CallScript()', None),
0x00F1: ('', 'CallScenario()', None),
0x00F3: ('', 'JumpScript()', None),
0x00F4: ('', 'TerminateExecutionOfScript()', None),
0x00F5: ('', 'SetEndOfScene()', None),
0x00F6: ('', 'RegisterLabel()', None),
0x00F7: ('', 'IsRegisteredLabel()', None),
0x00F8: ('', 'DisplayNumber()', None),
0x00F9: ('', 'DisplayStrings()', None),
0x00FA: ('', 'DumpMemory()', None),
0x00FC: ('', 'SelectCompiledScriptFile()', None),
0x00FF: ('', 'DisplayIP()', None),
0x0100: ('', 'GetTime()', None),
0x0101: ('', 'GetTickCount()', None),
0x0106: ('', 'SetCaptureImageForSaving()', None),
0x0107: ('', 'SetCommentForSaving()', None),
0x010A: ('', 'CallSavingWindow()', None),
0x010E: ('', 'ExecuteSiteJumping()', None),
0x010F: ('', 'LinkToSite()', None),
0x0110: ('', 'Wait()', None),
0x0111: ('', 'WaitForInput()', None),
0x0112: ('', 'InitializeTiming()', None),
0x0113: ('', 'WaitForTiming()', None),
0x0116: ('', 'EnableJumping()', None),
0x0117: ('', 'DisableJumping()', None),
0x0118: ('', 'SetSceneName()', None),
0x0119: ('', 'CancelSkipping()', None),
0x011A: ('', 'SetSceneInformation()', None),
0x011B: ('', 'SetDate()', None),
0x011C: ('', 'SetChapterInformation()', None),
0x0120: ('', 'SetValidityOfInput()', None),
0x0121: ('', 'SetValidityOfSkipping()', None),
0x0122: ('', 'SetValidityOfLoading()', None),
0x0123: ('', 'SetValidityOfSaving()', None),
0x0124: ('', 'ActivateScreenEffectForcedly()', None),
0x0125: ('', 'SetValidityOfAutomaticPageChanging()', None),
0x0126: ('', 'SetValidityOfUserEffectSpeed()', None),
0x0127: ('', 'SetValidityOfHScene()', None),
0x0128: ('', 'GetValidityOfGraphicsEffect()', None),
0x012C: ('', 'IsSkippingActive()', None),
0x012F: ('', 'GetExecutionMode()', None),
0x0130: ('', 'LoadCOMAP()', None),
0x0131: ('', 'GetIdentificationOfPC()', None),
0x0132: ('', 'CheckIdentificationOfPC()', None),
0x0133: ('', 'IsEpilogueInstalled()', None),
0x0134: ('', 'EnablePerformanceMeasurement()', None),
0x0135: ('', 'GetResultOfPerformanceMeasurement()', None),
0x0137: ('', 'GetScriptOfCG()', None),
0x0138: ('', 'SetNumberOfThumbnailOfCG()', None),
0x0139: ('', 'SetInformationOfThumbnailOfCG()', None),
0x013F: ('', 'InspectUsageConditionOfContents()', None),
0x01D0: ('', 'SetOverlapInformationOfSoftware()', None),
0x01D1: ('', 'SetMovieInformationOfSoftware()', None),
0x01D2: ('', 'SetTrialInformationOfSoftware()', None),
0x0141: ('', 'ClearMessage()', None),
0x0142: ('', 'StartNewLine()', None),
0x0143: ('', 'RegisterTextToHistory()', None),
0x0144: ('', 'DontRegisterTextToHistory()', None),
0x0145: ('', 'SetTextSpeed()', None),
0x0146: ('', 'SetDrawingPointOfMessage()', None),
0x0147: ('', 'SetDrawingPointOfMessageEx()', None),
0x014A: ('', 'DeleteAllKanas()', None),
0x014B: ('', 'RegisterKanaTemporarily()', None),
0x014C: ('', 'SetFontOfMessage()', None),
0x014D: ('', 'SetFontOfMessageEx()', None),
0x014E: ('', 'SetColorOfMonologue()', None),
0x014F: ('', 'SetColorOfWords()', None),
0x0150: ('', 'EnableWindow()', None),
0x0151: ('', 'DisableWindow()', None),
0x0152: ('', 'EnableWindowEx()', None),
0x0153: ('', 'DisableWindowEx()', None),
0x0157: ('', 'SpringText()', None),
0x0158: ('', 'SetStyleOfMessageWindow()', None),
0x0159: ('', 'SetStyleOfMessageSwinging()', None),
0x015A: ('', 'SetTextPosition()', None),
0x015C: ('', 'ChangeWindowColor()', None),
0x015D: ('', 'ChangeWindowDesign()', None),
0x015F: ('', 'SetVisibilityOfCaret()', None),
0x0160: ('', 'SetValidityOfPlayVoiceCheck()', None),
0x0161: ('', 'SetNameOfNotVoice()', None),
0x0170: ('', 'Select()', None),
0x0174: ('', 'InitializeSelectedItem()', None),
0x0175: ('', 'EnableItem()', None),
0x0176: ('', 'DisableItem()', None),
0x0178: ('', 'SelectIcon()', None),
0x017A: ('', 'SetTerminationCountOfIconSelecting()', None),
0x017E: ('', 'FadeIconSelecting()', None),
0x017F: ('', 'IsIconSelectingDisplaying()', None),
0x0180: ('', 'PlayBGM()', None),
0x0181: ('', 'PlayDividedBGM()', None),
0x0182: ('', 'PlanToPlayBGM()', None),
0x0184: ('', 'StopBGM()', None),
0x0185: ('', 'FadeOutBGM()', None),
0x0186: ('', 'ChangeVolumeOfBGM()', None),
0x0187: ('', 'ExecutePlannedControlOfBGM()', None),
0x0188: ('', 'StopMultiBGM()', None),
0x0189: ('', 'FadeOutMultiBGM()', None),
0x0190: ('', 'PlayStreamingSE()', None),
0x0191: ('', 'PlayDividedStreamingSE()', None),
0x0194: ('', 'StopStreamingSE()', None),
0x0195: ('', 'FadeOutStreamingSE()', None),
0x0196: ('', 'ChangeVolumeOfStreamingSE()', None),
0x0198: ('', 'PlayStreamingVoice()', None),
0x0199: ('', 'PlayDividedStreamingVoice()', None),
0x019C: ('', 'StopStreamingVoice()', None),
0x019D: ('', 'FadeOutStreamingVoice()', None),
0x019E: ('', 'ChangeVolumeOfStreamingVoice()', None),
0x01A0: ('', 'PlaySE()', None),
0x01A1: ('', 'PlaySESx()', None),
0x01A2: ('', 'StopSE()', None),
0x01A8: ('', 'FadeOutSE()', None),
0x01A3: ('', 'WaitToFinishSEPlaying()', None),
0x01A4: ('', 'PlayVoice()', None),
0x01A5: ('', 'PlayVoiceSx()', None),
0x01A6: ('', 'StopVoice()', None),
0x01A7: ('', 'WaitToFinishVoicePlaying()', None),
0x01B0: ('', 'SetValidityOfSynchronizedVoicePlaying()', None),
0x01B1: ('', 'RestrainSynchronizedVoicePlaying()', None),
0x01B2: ('', 'RequestToPlaySynchronizedVoice()', None),
0x01B4: ('', 'SetSceneNameForSynchronizedVoicePlaying()', None),
0x01B5: ('', 'RelateCharacterNameToSynchronizedVoice()', None),
0x01B6: ('', 'SetVoiceNumberForSynchronizedVoicePlaying()', None),
0x01B7: ('', 'SetAdjustmentForSynchronizedVoicePlaying()', None),
0x01BF: ('', 'PlayMovie()', None),
0x0220: ('', 'PreloadBitmap()', None),
0x0228: ('', 'MoveSight()', None),
0x0229: ('', 'WaitToFinishSightMoving()', None),
0x0230: ('', 'StartShakingOfAllObjects()', None),
0x0231: ('', 'TerminateShakingOfAllObjects()', None),
0x0232: ('', 'StartShakingOfWindow()', None),
0x0233: ('', 'TerminateShakingOfWindow()', None),
0x0234: ('', 'StartShakingOfBG()', None),
0x0235: ('', 'TerminateShakingOfBG()', None),
0x0236: ('', 'StartShakingOfBustshot()', None),
0x0237: ('', 'TerminateShakingOfBustshot()', None),
0x0238: ('', 'StartShakingOfSprite()', None),
0x0239: ('', 'TerminateShakingOfSprite()', None),
0x023C: ('', 'SetParameterForImageWaveringOfSprite()', None),
0x023D: ('', 'SetParameterForImageWaveringOfBustshot()', None),
0x0240: ('', 'DrawBG()', None),
0x0241: ('', 'DrawBGWithMask()', None),
0x0242: ('', 'DrawBGEx()', None),
0x0244: ('', 'FadeBG()', None),
0x0245: ('', 'FadeBGWithMask()', None),
0x0248: ('', 'ScrollBG()', None),
0x024C: ('', 'EnlargeBG()', None),
0x024D: ('', 'RotateBG()', None),
0x024E: ('', 'WaveBG()', None),
0x0258: ('', 'ControlMotionOfBG()', None),
0x025F: ('', 'WaitToFinishBGControlling()', None),
0x0260: ('', 'SetInitialPositionOfBG()', None),
0x0262: ('', 'SetLogicalZPositionOfBG()', None),
0x0268: ('', 'OptimizePositionOfBG()', None),
0x0280: ('', 'DrawScene()', None),
0x0281: ('', 'DrawSceneWithMask()', None),
0x0284: ('', 'ChangeScene()', None),
0x0288: ('', 'FadeScene()', None),
0x0289: ('', 'FadeSceneWithMask()', None),
0x028A: ('', 'FadeSceneEx()', None),
0x0290: ('', 'DrawSceneByVirtualBG()', None),
0x02C0: ('', 'DrawBustshot()', None),
0x02C1: ('', 'DrawBustshotEx()', None),
0x02C2: ('', 'MoveBustshot()', None),
0x02C3: ('', 'MoveBustshotEx()', None),
0x02C4: ('', 'ShiftBustshot()', None),
0x02C5: ('', 'ShiftBustshotEx()', None),
0x02C6: ('', 'ChangeBustshot()', None),
0x02C7: ('', 'ChangeBustshotEx()', None),
0x02C8: ('', 'FadeBustshot()', None),
0x02CA: ('', 'StretchBustshot()', None),
0x02CC: ('', 'PlanToChangeBustshot()', None),
0x02CE: ('', 'DrawBustshotWithFiltering()', None),
0x02D0: ('', 'DrawFace()', None),
0x02D2: ('', 'FadeFace()', None),
0x02DC: ('', 'ExecutePlannedControl()', None),
0x02DF: ('', 'WaitToFinishBustshotControlling()', None),
0x02E0: ('', 'GetPositionOfBustshot()', None),
0x02E4: ('', 'GetImageSizeOfBustshot()', None),
0x02E8: ('', 'OptimizePositionOfBustshot()', None),
0x02E9: ('', 'FixImageSizeOfBustshot()', None),
0x02EA: ('', 'ChangeOriginPositionOfImageOfBustshot()', None),
0x02F0: ('', 'EnablePerspectiveCollectionOfBustshot()', None),
0x0300: ('', 'DrawSprite()', None),
0x0301: ('', 'DrawSpriteEx()', None),
0x0302: ('', 'AnimateSprite()', None),
0x0303: ('', 'DrawSpriteForChainedBitmap()', None),
0x0304: ('', 'DrawSpriteWithFiltering()', None),
0x0306: ('', 'FadeSprite()', None),
0x0307: ('', 'FadeSpriteWithFiltering()', None),
0x0308: ('', 'MoveSprite()', None),
0x0309: ('', 'MoveSpriteEx()', None),
0x030C: ('', 'ScrollSpriteContinuously()', None),
0x030E: ('', 'ControlMotionOfSprite()', None),
0x031F: ('', 'WaitToFinishSpriteControlling()', None),
0x0320: ('', 'GetPositionOfSprite()', None),
0x0328: ('', 'OptimizePositionOfSprite()', None),
0x032C: ('', 'SuspendMovieRestartingOfSprite()', None),
0x0330: ('', 'SubordinateSprite()', None),
0x0331: ('', 'EmancipateSprite()', None),
0x0340: ('', 'EnableHorizontalGradation()', None),
0x0348: ('', 'DisableGradation()', None),
0x0350: ('', 'EnlargeScreen()', None),
0x0351: ('', 'GritScreen()', None),
0x0352: ('', 'RippleScreen()', None),
0x0353: ('', 'WaveScreen()', None),
0x0358: ('', 'DisableEffector()', None),
0x0360: ('', 'EnableBlur()', None),
0x0368: ('', 'DisableBlur()', None),
0x0380: ('', 'DrawFilm()', None),
0x0388: ('', 'FadeFilm()', None),
0x038D: ('', 'SetValidityOfFilmToFace()', None),
0x038E: ('', 'DisableWindowWhenControllingFilm()', None),
0x038F: ('', 'SetPriorityOfFilm()', None),
0x0390: ('', 'Blackout()', None),
0x0391: ('', 'Whiteout()', None),
0x0392: ('', 'WhiteoutBySA()', None),
0x0393: ('', 'Monochrome()', None),
0x0394: ('', 'Negative()', None),
0x03AF: ('', 'WaitToFinishFilmControlling()', None),
0x03C0: ('', 'EnableParticleScreen()', None),
0x03C1: ('', 'DisableParticleScreen()', None),
0x03C2: ('', 'VanishAllParticles()', None),
0x03C4: ('', 'SetParamaterForSnowfall()', None),
0x03C5: ('', 'SetParamaterForSnowstorm()', None),
0x03C6: ('', 'SetParamaterForSakurafubuki()', None),
0x03C7: ('', 'SetParamaterForFirefly()', None),
0x03C8: ('', 'SetParamaterForSpark()', None),
0x03C9: ('', 'SetParamaterForSnowfall_2()', None),
0x03CA: ('', 'SetParamaterForSakurafubuki_2()', None),
0x03D0: ('', 'SetValidityOfRainfall()', None),
0x03D2: ('', 'SetColorOfRain()', None),
0x03D4: ('', 'SetVectorOfSightForRainfall()', None),
0x03D5: ('', 'SetCameraAngleOfRainfall()', None),
0x03D6: ('', 'SetQuantityOfRainfall()', None),
0x03D8: ('', 'SetPriorityOfRainfallScreen()', None),
0x03F0: ('', 'ShakeScreen()', None),
0x03F1: ('', 'ShakeScreenSx()', None),
}

rops = {}

def make_ops():
	for op in range(0x400):
		if op not in ops:
			if op < 0x100:
				ops[op] = ('', 'f_%03x()' % op, None)
			elif 0x100 <= op < 0x140:
				ops[op] = ('', 'sys_::f_%03x()' % op, None)
			elif 0x140 <= op < 0x160:
				ops[op] = ('', 'msg_::f_%03x()' % op, None)
			elif 0x160 <= op < 0x180:
				ops[op] = ('', 'slct::f_%03x()' % op, None)
			elif 0x180 <= op < 0x200:
				ops[op] = ('', 'snd_::f_%03x()' % op, None)
			elif 0x200 <= op < 0x400:
				ops[op] = ('', 'grp_::f_%03x()' % op, None)
				
def make_rops():
	for op in ops:
		fcn, = re_fcn.match(ops[op][1]).groups()
		rops[fcn] = op
	
make_ops()
make_rops()
