#pragma		once

// ****************************************************************
// 描画
// ================================================================

// 通常
#define		__DRAW_SUB_NORMAL \
					__GET_SRC_R_EBX __SET_R_SUB \
					__GET_SRC_G_EBX __SET_G_SUB \
					__GET_SRC_B_EBX __SET_B_SUB

// 透明度
#define		__DRAW_SUB_TR \
					__GET_SRC_R_EBX __SET_R_SUB_TR \
					__GET_SRC_G_EBX __SET_G_SUB_TR \
					__GET_SRC_B_EBX __SET_B_SUB_TR

// 色味 通常
#define		__DRAW_SUB_BRIGHT \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_SUB

// 色味 透明度
#define		__DRAW_SUB_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_SUB_TR

// 変色 通常
#define		__DRAW_SUB_COLOR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_SUB

// 変色 透明度
#define		__DRAW_SUB_COLOR_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_SUB_TR

// 変色 色味 通常
#define		__DRAW_SUB_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB

// 変色 色味 透明度
#define		__DRAW_SUB_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// 反転 通常
#define		__DRAW_SUB_REVERSE \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_SUB

// 反転 透明度
#define		__DRAW_SUB_REVERSE_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_SUB_TR

// 反転 色味 通常
#define		__DRAW_SUB_REVERSE_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB

// 反転 色味 透明度
#define		__DRAW_SUB_REVERSE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB_TR

// 反転 変色 通常
#define		__DRAW_SUB_REVERSE_COLOR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB

// 反転 変色 透明度
#define		__DRAW_SUB_REVERSE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB_TR

// 反転 変色 色味 通常
#define		__DRAW_SUB_REVERSE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB

// 反転 変色 色味 透明度
#define		__DRAW_SUB_REVERSE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// モノ 通常
#define		__DRAW_SUB_MONO \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_SUB

// モノ 透明度
#define		__DRAW_SUB_MONO_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_SUB_TR

// モノ 色味 通常
#define		__DRAW_SUB_MONO_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_SUB

// モノ 色味 透明度
#define		__DRAW_SUB_MONO_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_SUB_TR

// モノ 変色 通常
#define		__DRAW_SUB_MONO_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_SUB

// モノ 変色 透明度
#define		__DRAW_SUB_MONO_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_SUB_TR

// モノ 変色 色味 通常
#define		__DRAW_SUB_MONO_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB

// モノ 変色 色味 透明度
#define		__DRAW_SUB_MONO_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// モノ 反転 通常
#define		__DRAW_SUB_MONO_REVERSE \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_SUB

// モノ 反転 透明度
#define		__DRAW_SUB_MONO_REVERSE_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_SUB_TR

// モノ 反転 色味 通常
#define		__DRAW_SUB_MONO_REVERSE_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB

// モノ 反転 色味 透明度
#define		__DRAW_SUB_MONO_REVERSE_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB_TR

// モノ 反転 変色 通常
#define		__DRAW_SUB_MONO_REVERSE_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB

// モノ 反転 変色 透明度
#define		__DRAW_SUB_MONO_REVERSE_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB_TR

// モノ 反転 変色 色味 通常
#define		__DRAW_SUB_MONO_REVERSE_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB

// モノ 反転 変色 色味 透明度
#define		__DRAW_SUB_MONO_REVERSE_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 通常
#define		__DRAW_SUB_TILE_NORMAL \
					__GET_SRC_R_EBX __SET_R_SUB_TR \
					__GET_SRC_G_EBX __SET_G_SUB_TR \
					__GET_SRC_B_EBX __SET_B_SUB_TR

// タイル 透明度
#define		__DRAW_SUB_TILE_TR \
					__GET_SRC_R_EBX __SET_R_SUB_TR \
					__GET_SRC_G_EBX __SET_G_SUB_TR \
					__GET_SRC_B_EBX __SET_B_SUB_TR

// タイル 色味 通常
#define		__DRAW_SUB_TILE_BRIGHT \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 色味 透明度
#define		__DRAW_SUB_TILE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 変色 通常
#define		__DRAW_SUB_TILE_COLOR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_SUB_TR

// タイル 変色 透明度
#define		__DRAW_SUB_TILE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_SUB_TR

// タイル 変色 色味 通常
#define		__DRAW_SUB_TILE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 変色 色味 透明度
#define		__DRAW_SUB_TILE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 反転 通常
#define		__DRAW_SUB_TILE_REVERSE \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_SUB_TR

// タイル 反転 透明度
#define		__DRAW_SUB_TILE_REVERSE_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_SUB_TR

// タイル 反転 色味 通常
#define		__DRAW_SUB_TILE_REVERSE_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 反転 色味 透明度
#define		__DRAW_SUB_TILE_REVERSE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 反転 変色 通常
#define		__DRAW_SUB_TILE_REVERSE_COLOR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB_TR

// タイル 反転 変色 透明度
#define		__DRAW_SUB_TILE_REVERSE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB_TR

// タイル 反転 変色 色味 通常
#define		__DRAW_SUB_TILE_REVERSE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル 反転 変色 色味 透明度
#define		__DRAW_SUB_TILE_REVERSE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 通常
#define		__DRAW_SUB_TILE_MONO \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_SUB_TR

// タイル モノ 透明度
#define		__DRAW_SUB_TILE_MONO_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_SUB_TR

// タイル モノ 色味 通常
#define		__DRAW_SUB_TILE_MONO_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 色味 透明度
#define		__DRAW_SUB_TILE_MONO_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 変色 通常
#define		__DRAW_SUB_TILE_MONO_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_SUB_TR

// タイル モノ 変色 透明度
#define		__DRAW_SUB_TILE_MONO_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_SUB_TR

// タイル モノ 変色 色味 通常
#define		__DRAW_SUB_TILE_MONO_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 変色 色味 透明度
#define		__DRAW_SUB_TILE_MONO_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 反転 通常
#define		__DRAW_SUB_TILE_MONO_REVERSE \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_SUB_TR

// タイル モノ 反転 透明度
#define		__DRAW_SUB_TILE_MONO_REVERSE_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_SUB_TR

// タイル モノ 反転 色味 通常
#define		__DRAW_SUB_TILE_MONO_REVERSE_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 反転 色味 透明度
#define		__DRAW_SUB_TILE_MONO_REVERSE_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 反転 変色 通常
#define		__DRAW_SUB_TILE_MONO_REVERSE_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB_TR

// タイル モノ 反転 変色 透明度
#define		__DRAW_SUB_TILE_MONO_REVERSE_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_SUB_TR

// タイル モノ 反転 変色 色味 通常
#define		__DRAW_SUB_TILE_MONO_REVERSE_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

// タイル モノ 反転 変色 色味 透明度
#define		__DRAW_SUB_TILE_MONO_REVERSE_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_SUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_SUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_SUB_TR

