#pragma		once

// ****************************************************************
// 描画
// ================================================================

// 通常
#define		__DRAW_BLD_NORMAL \
					__GET_SRC_R_EAX __SET_R_BLD \
					__GET_SRC_G_EAX __SET_G_BLD \
					__GET_SRC_B_EAX __SET_B_BLD \
					__SET_A_BLD

// 透明度
#define		__DRAW_BLD_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __SET_R_BLD_TR \
					__GET_SRC_G_EBX __SET_G_BLD_TR \
					__GET_SRC_B_EBX __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// 色味 通常
#define		__DRAW_BLD_BRIGHT \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// 色味 透明度
#define		__DRAW_BLD_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// 変色 通常
#define		__DRAW_BLD_COLOR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_BLD \
					__SET_A_BLD

// 変色 透明度
#define		__DRAW_BLD_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// 変色 色味 通常
#define		__DRAW_BLD_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// 変色 色味 透明度
#define		__DRAW_BLD_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// 反転 通常
#define		__DRAW_BLD_REVERSE \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_BLD \
					__SET_A_BLD

// 反転 透明度
#define		__DRAW_BLD_REVERSE_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// 反転 色味 通常
#define		__DRAW_BLD_REVERSE_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// 反転 色味 透明度
#define		__DRAW_BLD_REVERSE_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// 反転 変色 通常
#define		__DRAW_BLD_REVERSE_COLOR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD \
					__SET_A_BLD

// 反転 変色 透明度
#define		__DRAW_BLD_REVERSE_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// 反転 変色 色味 通常
#define		__DRAW_BLD_REVERSE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// 反転 変色 色味 透明度
#define		__DRAW_BLD_REVERSE_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 通常
#define		__DRAW_BLD_MONO \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_BLD \
					__SET_A_BLD

// モノ 透明度
#define		__DRAW_BLD_MONO_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 色味 通常
#define		__DRAW_BLD_MONO_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// モノ 色味 透明度
#define		__DRAW_BLD_MONO_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 変色 通常
#define		__DRAW_BLD_MONO_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_BLD \
					__SET_A_BLD

// モノ 変色 透明度
#define		__DRAW_BLD_MONO_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 変色 色味 通常
#define		__DRAW_BLD_MONO_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// モノ 変色 色味 透明度
#define		__DRAW_BLD_MONO_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 反転 通常
#define		__DRAW_BLD_MONO_REVERSE \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_BLD \
					__SET_A_BLD

// モノ 反転 透明度
#define		__DRAW_BLD_MONO_REVERSE_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 反転 色味 通常
#define		__DRAW_BLD_MONO_REVERSE_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// モノ 反転 色味 透明度
#define		__DRAW_BLD_MONO_REVERSE_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 反転 変色 通常
#define		__DRAW_BLD_MONO_REVERSE_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD \
					__SET_A_BLD

// モノ 反転 変色 透明度
#define		__DRAW_BLD_MONO_REVERSE_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// モノ 反転 変色 色味 通常
#define		__DRAW_BLD_MONO_REVERSE_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD \
					__SET_A_BLD

// モノ 反転 変色 色味 透明度
#define		__DRAW_BLD_MONO_REVERSE_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 通常
#define		__DRAW_BLD_TILE_NORMAL \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __SET_R_BLD_TR \
					__GET_SRC_G_EBX __SET_G_BLD_TR \
					__GET_SRC_B_EBX __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 透明度
#define		__DRAW_BLD_TILE_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __SET_R_BLD_TR \
					__GET_SRC_G_EBX __SET_G_BLD_TR \
					__GET_SRC_B_EBX __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 色味 通常
#define		__DRAW_BLD_TILE_BRIGHT \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 色味 透明度
#define		__DRAW_BLD_TILE_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 変色 通常
#define		__DRAW_BLD_TILE_COLOR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 変色 透明度
#define		__DRAW_BLD_TILE_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 変色 色味 通常
#define		__DRAW_BLD_TILE_COLOR_BRIGHT \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 変色 色味 透明度
#define		__DRAW_BLD_TILE_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 通常
#define		__DRAW_BLD_TILE_REVERSE \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 透明度
#define		__DRAW_BLD_TILE_REVERSE_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 色味 通常
#define		__DRAW_BLD_TILE_REVERSE_BRIGHT \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 色味 透明度
#define		__DRAW_BLD_TILE_REVERSE_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 変色 通常
#define		__DRAW_BLD_TILE_REVERSE_COLOR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 変色 透明度
#define		__DRAW_BLD_TILE_REVERSE_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 変色 色味 通常
#define		__DRAW_BLD_TILE_REVERSE_COLOR_BRIGHT \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル 反転 変色 色味 透明度
#define		__DRAW_BLD_TILE_REVERSE_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 通常
#define		__DRAW_BLD_TILE_MONO \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 透明度
#define		__DRAW_BLD_TILE_MONO_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 色味 通常
#define		__DRAW_BLD_TILE_MONO_BRIGHT \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 色味 透明度
#define		__DRAW_BLD_TILE_MONO_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 変色 通常
#define		__DRAW_BLD_TILE_MONO_COLOR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 変色 透明度
#define		__DRAW_BLD_TILE_MONO_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 変色 色味 通常
#define		__DRAW_BLD_TILE_MONO_COLOR_BRIGHT \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 変色 色味 透明度
#define		__DRAW_BLD_TILE_MONO_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 通常
#define		__DRAW_BLD_TILE_MONO_REVERSE \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 透明度
#define		__DRAW_BLD_TILE_MONO_REVERSE_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 色味 通常
#define		__DRAW_BLD_TILE_MONO_REVERSE_BRIGHT \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 色味 透明度
#define		__DRAW_BLD_TILE_MONO_REVERSE_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 変色 通常
#define		__DRAW_BLD_TILE_MONO_REVERSE_COLOR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 変色 透明度
#define		__DRAW_BLD_TILE_MONO_REVERSE_COLOR_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 変色 色味 通常
#define		__DRAW_BLD_TILE_MONO_REVERSE_COLOR_BRIGHT \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

// タイル モノ 反転 変色 色味 透明度
#define		__DRAW_BLD_TILE_MONO_REVERSE_COLOR_BRIGHT_TR \
					__BEFOR_ALPHABLEND \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_BLD_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_BLD_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_BLD_TR \
					__AFTER_ALPHABLEND

