#pragma		once

// ****************************************************************
// 描画
// ================================================================

// 通常
#define		__DRAW_FLT_NORMAL \
					__GET_SRC_R_EBX __SET_R_FLT \
					__GET_SRC_G_EBX __SET_G_FLT \
					__GET_SRC_B_EBX __SET_B_FLT

// 透明度
#define		__DRAW_FLT_TR \
					__GET_SRC_R_EBX __SET_R_FLT_TR \
					__GET_SRC_G_EBX __SET_G_FLT_TR \
					__GET_SRC_B_EBX __SET_B_FLT_TR

// 色味 通常
#define		__DRAW_FLT_BRIGHT \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_FLT

// 色味 透明度
#define		__DRAW_FLT_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_FLT_TR

// 変色 通常
#define		__DRAW_FLT_COLOR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_FLT

// 変色 透明度
#define		__DRAW_FLT_COLOR_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_FLT_TR

// 変色 色味 通常
#define		__DRAW_FLT_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT

// 変色 色味 透明度
#define		__DRAW_FLT_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// 反転 通常
#define		__DRAW_FLT_REVERSE \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_FLT

// 反転 透明度
#define		__DRAW_FLT_REVERSE_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_FLT_TR

// 反転 色味 通常
#define		__DRAW_FLT_REVERSE_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT

// 反転 色味 透明度
#define		__DRAW_FLT_REVERSE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT_TR

// 反転 変色 通常
#define		__DRAW_FLT_REVERSE_COLOR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT

// 反転 変色 透明度
#define		__DRAW_FLT_REVERSE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT_TR

// 反転 変色 色味 通常
#define		__DRAW_FLT_REVERSE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT

// 反転 変色 色味 透明度
#define		__DRAW_FLT_REVERSE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// モノ 通常
#define		__DRAW_FLT_MONO \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_FLT

// モノ 透明度
#define		__DRAW_FLT_MONO_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_FLT_TR

// モノ 色味 通常
#define		__DRAW_FLT_MONO_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_FLT

// モノ 色味 透明度
#define		__DRAW_FLT_MONO_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_FLT_TR

// モノ 変色 通常
#define		__DRAW_FLT_MONO_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_FLT

// モノ 変色 透明度
#define		__DRAW_FLT_MONO_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_FLT_TR

// モノ 変色 色味 通常
#define		__DRAW_FLT_MONO_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT

// モノ 変色 色味 透明度
#define		__DRAW_FLT_MONO_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// モノ 反転 通常
#define		__DRAW_FLT_MONO_REVERSE \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_FLT

// モノ 反転 透明度
#define		__DRAW_FLT_MONO_REVERSE_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_FLT_TR

// モノ 反転 色味 通常
#define		__DRAW_FLT_MONO_REVERSE_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT

// モノ 反転 色味 透明度
#define		__DRAW_FLT_MONO_REVERSE_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT_TR

// モノ 反転 変色 通常
#define		__DRAW_FLT_MONO_REVERSE_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT

// モノ 反転 変色 透明度
#define		__DRAW_FLT_MONO_REVERSE_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT_TR

// モノ 反転 変色 色味 通常
#define		__DRAW_FLT_MONO_REVERSE_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT

// モノ 反転 変色 色味 透明度
#define		__DRAW_FLT_MONO_REVERSE_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 通常
#define		__DRAW_FLT_TILE_NORMAL \
					__GET_SRC_R_EBX __SET_R_FLT_TR \
					__GET_SRC_G_EBX __SET_G_FLT_TR \
					__GET_SRC_B_EBX __SET_B_FLT_TR

// タイル 透明度
#define		__DRAW_FLT_TILE_TR \
					__GET_SRC_R_EBX __SET_R_FLT_TR \
					__GET_SRC_G_EBX __SET_G_FLT_TR \
					__GET_SRC_B_EBX __SET_B_FLT_TR

// タイル 色味 通常
#define		__DRAW_FLT_TILE_BRIGHT \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 色味 透明度
#define		__DRAW_FLT_TILE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 変色 通常
#define		__DRAW_FLT_TILE_COLOR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_FLT_TR

// タイル 変色 透明度
#define		__DRAW_FLT_TILE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_FLT_TR

// タイル 変色 色味 通常
#define		__DRAW_FLT_TILE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 変色 色味 透明度
#define		__DRAW_FLT_TILE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 反転 通常
#define		__DRAW_FLT_TILE_REVERSE \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_FLT_TR

// タイル 反転 透明度
#define		__DRAW_FLT_TILE_REVERSE_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_FLT_TR

// タイル 反転 色味 通常
#define		__DRAW_FLT_TILE_REVERSE_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 反転 色味 透明度
#define		__DRAW_FLT_TILE_REVERSE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 反転 変色 通常
#define		__DRAW_FLT_TILE_REVERSE_COLOR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT_TR

// タイル 反転 変色 透明度
#define		__DRAW_FLT_TILE_REVERSE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT_TR

// タイル 反転 変色 色味 通常
#define		__DRAW_FLT_TILE_REVERSE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル 反転 変色 色味 透明度
#define		__DRAW_FLT_TILE_REVERSE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 通常
#define		__DRAW_FLT_TILE_MONO \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_FLT_TR

// タイル モノ 透明度
#define		__DRAW_FLT_TILE_MONO_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_FLT_TR

// タイル モノ 色味 通常
#define		__DRAW_FLT_TILE_MONO_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 色味 透明度
#define		__DRAW_FLT_TILE_MONO_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 変色 通常
#define		__DRAW_FLT_TILE_MONO_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_FLT_TR

// タイル モノ 変色 透明度
#define		__DRAW_FLT_TILE_MONO_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_FLT_TR

// タイル モノ 変色 色味 通常
#define		__DRAW_FLT_TILE_MONO_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 変色 色味 透明度
#define		__DRAW_FLT_TILE_MONO_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 反転 通常
#define		__DRAW_FLT_TILE_MONO_REVERSE \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_FLT_TR

// タイル モノ 反転 透明度
#define		__DRAW_FLT_TILE_MONO_REVERSE_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_FLT_TR

// タイル モノ 反転 色味 通常
#define		__DRAW_FLT_TILE_MONO_REVERSE_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 反転 色味 透明度
#define		__DRAW_FLT_TILE_MONO_REVERSE_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 反転 変色 通常
#define		__DRAW_FLT_TILE_MONO_REVERSE_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT_TR

// タイル モノ 反転 変色 透明度
#define		__DRAW_FLT_TILE_MONO_REVERSE_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_FLT_TR

// タイル モノ 反転 変色 色味 通常
#define		__DRAW_FLT_TILE_MONO_REVERSE_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

// タイル モノ 反転 変色 色味 透明度
#define		__DRAW_FLT_TILE_MONO_REVERSE_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_FLT_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_FLT_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_FLT_TR

