#pragma		once

// ****************************************************************
// 描画
// ================================================================

// 通常
#define		__DRAW_RSUB_NORMAL \
					__GET_SRC_R_EBX __SET_R_RSUB \
					__GET_SRC_G_EBX __SET_G_RSUB \
					__GET_SRC_B_EBX __SET_B_RSUB

// 透明度
#define		__DRAW_RSUB_TR \
					__GET_SRC_R_EBX __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __SET_B_RSUB_TR

// 色味 通常
#define		__DRAW_RSUB_BRIGHT \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_RSUB

// 色味 透明度
#define		__DRAW_RSUB_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_RSUB_TR

// 変色 通常
#define		__DRAW_RSUB_COLOR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_RSUB

// 変色 透明度
#define		__DRAW_RSUB_COLOR_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_RSUB_TR

// 変色 色味 通常
#define		__DRAW_RSUB_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB

// 変色 色味 透明度
#define		__DRAW_RSUB_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// 反転 通常
#define		__DRAW_RSUB_REVERSE \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_RSUB

// 反転 透明度
#define		__DRAW_RSUB_REVERSE_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_RSUB_TR

// 反転 色味 通常
#define		__DRAW_RSUB_REVERSE_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB

// 反転 色味 透明度
#define		__DRAW_RSUB_REVERSE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB_TR

// 反転 変色 通常
#define		__DRAW_RSUB_REVERSE_COLOR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB

// 反転 変色 透明度
#define		__DRAW_RSUB_REVERSE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB_TR

// 反転 変色 色味 通常
#define		__DRAW_RSUB_REVERSE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB

// 反転 変色 色味 透明度
#define		__DRAW_RSUB_REVERSE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// モノ 通常
#define		__DRAW_RSUB_MONO \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_RSUB

// モノ 透明度
#define		__DRAW_RSUB_MONO_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_RSUB_TR

// モノ 色味 通常
#define		__DRAW_RSUB_MONO_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_RSUB

// モノ 色味 透明度
#define		__DRAW_RSUB_MONO_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_RSUB_TR

// モノ 変色 通常
#define		__DRAW_RSUB_MONO_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_RSUB

// モノ 変色 透明度
#define		__DRAW_RSUB_MONO_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_RSUB_TR

// モノ 変色 色味 通常
#define		__DRAW_RSUB_MONO_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB

// モノ 変色 色味 透明度
#define		__DRAW_RSUB_MONO_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// モノ 反転 通常
#define		__DRAW_RSUB_MONO_REVERSE \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_RSUB

// モノ 反転 透明度
#define		__DRAW_RSUB_MONO_REVERSE_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_RSUB_TR

// モノ 反転 色味 通常
#define		__DRAW_RSUB_MONO_REVERSE_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB

// モノ 反転 色味 透明度
#define		__DRAW_RSUB_MONO_REVERSE_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB_TR

// モノ 反転 変色 通常
#define		__DRAW_RSUB_MONO_REVERSE_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB

// モノ 反転 変色 透明度
#define		__DRAW_RSUB_MONO_REVERSE_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB_TR

// モノ 反転 変色 色味 通常
#define		__DRAW_RSUB_MONO_REVERSE_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB

// モノ 反転 変色 色味 透明度
#define		__DRAW_RSUB_MONO_REVERSE_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 通常
#define		__DRAW_RSUB_TILE_NORMAL \
					__GET_SRC_R_EBX __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __SET_B_RSUB_TR

// タイル 透明度
#define		__DRAW_RSUB_TILE_TR \
					__GET_SRC_R_EBX __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __SET_B_RSUB_TR

// タイル 色味 通常
#define		__DRAW_RSUB_TILE_BRIGHT \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 色味 透明度
#define		__DRAW_RSUB_TILE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 変色 通常
#define		__DRAW_RSUB_TILE_COLOR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_RSUB_TR

// タイル 変色 透明度
#define		__DRAW_RSUB_TILE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __SET_B_RSUB_TR

// タイル 変色 色味 通常
#define		__DRAW_RSUB_TILE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 変色 色味 透明度
#define		__DRAW_RSUB_TILE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 反転 通常
#define		__DRAW_RSUB_TILE_REVERSE \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_RSUB_TR

// タイル 反転 透明度
#define		__DRAW_RSUB_TILE_REVERSE_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __SET_B_RSUB_TR

// タイル 反転 色味 通常
#define		__DRAW_RSUB_TILE_REVERSE_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 反転 色味 透明度
#define		__DRAW_RSUB_TILE_REVERSE_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 反転 変色 通常
#define		__DRAW_RSUB_TILE_REVERSE_COLOR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB_TR

// タイル 反転 変色 透明度
#define		__DRAW_RSUB_TILE_REVERSE_COLOR_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB_TR

// タイル 反転 変色 色味 通常
#define		__DRAW_RSUB_TILE_REVERSE_COLOR_BRIGHT \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル 反転 変色 色味 透明度
#define		__DRAW_RSUB_TILE_REVERSE_COLOR_BRIGHT_TR \
					__GET_SRC_R_EBX __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 通常
#define		__DRAW_RSUB_TILE_MONO \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_RSUB_TR

// タイル モノ 透明度
#define		__DRAW_RSUB_TILE_MONO_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __SET_B_RSUB_TR

// タイル モノ 色味 通常
#define		__DRAW_RSUB_TILE_MONO_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 色味 透明度
#define		__DRAW_RSUB_TILE_MONO_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 変色 通常
#define		__DRAW_RSUB_TILE_MONO_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_RSUB_TR

// タイル モノ 変色 透明度
#define		__DRAW_RSUB_TILE_MONO_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __SET_B_RSUB_TR

// タイル モノ 変色 色味 通常
#define		__DRAW_RSUB_TILE_MONO_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 変色 色味 透明度
#define		__DRAW_RSUB_TILE_MONO_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 反転 通常
#define		__DRAW_RSUB_TILE_MONO_REVERSE \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_RSUB_TR

// タイル モノ 反転 透明度
#define		__DRAW_RSUB_TILE_MONO_REVERSE_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __SET_B_RSUB_TR

// タイル モノ 反転 色味 通常
#define		__DRAW_RSUB_TILE_MONO_REVERSE_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 反転 色味 透明度
#define		__DRAW_RSUB_TILE_MONO_REVERSE_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 反転 変色 通常
#define		__DRAW_RSUB_TILE_MONO_REVERSE_COLOR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB_TR

// タイル モノ 反転 変色 透明度
#define		__DRAW_RSUB_TILE_MONO_REVERSE_COLOR_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __SET_B_RSUB_TR

// タイル モノ 反転 変色 色味 通常
#define		__DRAW_RSUB_TILE_MONO_REVERSE_COLOR_BRIGHT \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

// タイル モノ 反転 変色 色味 透明度
#define		__DRAW_RSUB_TILE_MONO_REVERSE_COLOR_BRIGHT_TR \
					__READY_MONO \
					__GET_SRC_R_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_R __CNV_BRIGHT_R __SET_R_RSUB_TR \
					__GET_SRC_G_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_G __CNV_BRIGHT_G __SET_G_RSUB_TR \
					__GET_SRC_B_EBX __CNV_MONO __CNV_REVERSE __CNV_COLOR_B __CNV_BRIGHT_B __SET_B_RSUB_TR

