#pragma once

#include "tonad3d3_effect_lighting_and_shading_shader.h"

// 統一規格を司るようなイメージのファイル
// 変数名を変更したくなった時にこのファイルだけを変更すればそのまま動く用にする為
// 例) In.Pos 表記だったものを in.pos に変えたい時など

namespace NT3
{

enum EFFECT_VAL_TYPE {
	// EFFECT_VAL_TYPE_VS_LOCAL_,
	// EFFECT_VAL_TYPE_VS_WORLD_,
	// EFFECT_VAL_TYPE_VS_
	// EFFECT_VAL_TYPE_PS_

	// 共通
	EFFECT_VAL_TYPE_VS_LOCAL_POS,
	EFFECT_VAL_TYPE_VS_WORLD_POS,
	EFFECT_VAL_TYPE_VS_LOCAL_NORMAL,
	EFFECT_VAL_TYPE_VS_WORLD_NORMAL,
	EFFECT_VAL_TYPE_VS_LIGHT_BRIGHTNESS,

	EFFECT_VAL_TYPE_PS_LIGHT_BRIGHTNESS,


	// 種類毎
	EFFECT_VAL_TYPE_VSO_DIFFUSE,
	EFFECT_VAL_TYPE_VSO_SPECULAR,
	EFFECT_VAL_TYPE_VSO_AMBIENT,
	EFFECT_VAL_TYPE_VSO_WORLD_EYE,
	EFFECT_VAL_TYPE_VSO_WORLD_NORMAL,
	EFFECT_VAL_TYPE_VSO_WORLD_POS,
	EFFECT_VAL_TYPE_VSO_RIM_LIGHT_POWER,
	EFFECT_VAL_TYPE_VSO_SHADOW_MAP_UV,
	EFFECT_VAL_TYPE_VSO_DEPTH,
	EFFECT_VAL_TYPE_VSO_RIM_LIGHT_COLOR,
	EFFECT_VAL_TYPE_VSO_WORLD_TANGENT,
	EFFECT_VAL_TYPE_VSO_WORLD_BINORMAL,

	EFFECT_VAL_TYPE_PSI_DIFFUSE,
	EFFECT_VAL_TYPE_PSI_SPECULAR,
	EFFECT_VAL_TYPE_PSI_AMBIENT,
	EFFECT_VAL_TYPE_PSI_WORLD_EYE,
	EFFECT_VAL_TYPE_PSI_WORLD_NORMAL,
	EFFECT_VAL_TYPE_PSI_WORLD_POS,
	EFFECT_VAL_TYPE_PSI_RIM_LIGHT_POWER,
	EFFECT_VAL_TYPE_PSI_SHADOW_MAP_UV,
	EFFECT_VAL_TYPE_PSI_DEPTH,
	EFFECT_VAL_TYPE_PSI_RIM_LIGHT_COLOR,
	EFFECT_VAL_TYPE_PSI_WORLD_TANGENT,
	EFFECT_VAL_TYPE_PSI_WORLD_BINORMAL,
};

class C_d3d_effect_source_val_manager {
public:
	C_d3d_effect_source_val_manager();
	~C_d3d_effect_source_val_manager();

	// タイプによって変わる物
	MBSTR get_val_name(EFFECT_VAL_TYPE evt, LIGHTING_TYPE lt, SHADING_TYPE st);
	// 全タイプ共通
	MBSTR get_val_name(EFFECT_VAL_TYPE evt);
};

// タイプによって変わる物
MBSTR get_effect_val_name(EFFECT_VAL_TYPE evt, LIGHTING_TYPE lt, SHADING_TYPE st);
// 全タイプ共通
MBSTR get_effect_val_name(EFFECT_VAL_TYPE evt);


}